### ISSUE TITLE
Where to get the APK?

### ISSUE THREAD

**Issue by IzzySoft** [jff99/KeyCip#1]
I sthere any place users can obtain the APK from to give your app a try? Maybe you could attach it to its corresponding release? Thanks in advance!

**Comment by jff99** [comment]
Hi, thanks for opening an issue. Unfortunately, I do not have my computer with me right now. As soon as I get home, I will add to the release. 

In the meantime, it could be downloaded through the Google Play: https://play.google.com/store/apps/details?id=jorgeff99.keymyinfo

**Comment by IzzySoft** [comment]
Wonderful, thanks a lot! And no, I don't have access to Play – same for many of our "privacy fraction"; we use [F-Droid](https://f-droid.org/) instead, where the privacy-friendly FOSS apps live. But maybe we can strike a deal: you keep attaching the APK – and I will add and fetch it to [my repo](https://apt.izzysoft.de/fdroid) to make it available outside of Play in an easy-to-find and easy-to-maintain way. If you wish I could then also help you move on to F-Droid's own repository, which has a bit stricter rules than mine, takes a bit longer to process – but has a higher standing as well.

Looking forward to make it happen :smiley:

**Comment by jff99** [comment]
Hi, I have added the APK to the version release. You are allowed to upload the APK to your Fdroid repo (just link it to this repository). Moreover, I will appreciate your help to create my own repository there

**Comment by IzzySoft** [comment]
Thanks! Just noticed that the tag v1.0.0 ships version 2.4. Maybe you want to align the two (guess it's the tag that should be renamed :wink:) Further, the app is build with the debug flag set (ApplicationDebuggable), which is not intended for releases.

Apart from that, everything looks fine – and your app should [show up here](https://apt.izzysoft.de/fdroid/index/apk/jorgeff99.keymyinfo) around 6 pm UTC with the next sync. As for setting up your own F-Droid repo: may I refer you to my corresponding article series? Two parts for that task (a basic one, and one with improvements):

* [Setting up a simple binary F-Droid repo](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo)
* [Extend the „simple binary repo“: Screenshots & more](https://android.izzysoft.de/articles/named/fdroid-simple-binary-repo-2)

"Simple binary repo" is what I use. If you want to go the full path to a fully fledged F-Droid repo including all build parts, I cannot really help with that – I'm not a dev myself. But if you want to bring your app to F-Droid's own repo, I can provide you with the initial Fastlane metadata structure for your app (via PR), as that's set up for my repo now already.

Oh, and [there's a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to use it to link to your app's presence in my repo :smiley:

**Comment by jff99** [comment]
I have updated the APK file (just to let you know in case you want to change in your Fdroid repo).Also the name of the release has been updated.

**Comment by beaglesnuf** [comment]
Moreover, if you could publish the sha256 hash of the apk (for integrity) per release and the cert fingerprint of your signing key (for authenticity) it would be of great help with the Android trust-on-first-use model where the first install of an app is pinned to the cert of that install. What i currently have is:

`SHA256 (KeyCip.apk) = a186d3fc7888822b4078abc2d353ad3c7331a3904d4dc1e4c5b2aca4624a4b4e`

`Signer #1 certificate DN: CN=Jorge Fernández Fonseca, OU=KeyCip, O=KeyCip, L=Madrid, ST=Madrid, C=ES
Signer #1 certificate SHA-256 digest: 2b2561219ed3271b29de3bc3e88506114eee85c5d7309270821621c0b39f1548`

But there is no way I can be absolutely sure that the apk I have is indeed the apk you released here on GitHub (even though it was downloaded from GitHub) until I can match those against an officially published hash/print.

**Comment by IzzySoft** [comment]
> I have updated the APK file (just to let you know in case you want to change in your Fdroid repo).Also the name of the release has been updated.

Thanks! As the version number did not change (it's still 2.4), my updater ignored it (and I was AFK). Do you plan another release in the near future? That would then be picked up automatically. Otherwise I can of course pick the new APK manually to replace what's in my repo now, to get rid of the debug flag. Just let me know :wink:

**Comment by jff99** [comment]
New version has been published, adding the suggestions of @beaglesnuf. Thanks to both!

**Comment by IzzySoft** [comment]
Yupp, thanks! My updater found and picked it. I just removed the AntiFeature, so that will be gone with the next sync then. If there are no more open questions left, feel free to close the issue :smiley: And be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link to the new download (and update) possibility :smile:

**Comment by IzzySoft** [comment]
Thanks for "badging" :smiley:

**Comment by licaon-kter** [comment]
The main readme says `[checked] Add the app to Fdroid Store` but https://search.f-droid.org/?q=keychip I can't find it :(
