### ISSUE TITLE
22.4: General Comments

### ISSUE THREAD

**Issue by beaglesnuf** [jff99/KeyCip#2]
1. KeyCip --> Keyboard: Youtube to YouTube. Better yet, because of the YouTube association with Google, perhaps an alternative media hosting servive such as PeerTube could be leveraged for the privacy-conscious.

2. KeyCip --> Settings: Github to GitHub.

3. Conventional nomenclature for encrypting content to oneself is typically 'self'.  We see this in PGP/GnuPG and Signal (e.g. Note to Self). Under 'Select a contact' the term 'Self' may be preferrable to 'Me'

**Comment by jff99** [comment]
Changed text for all the words above mentioned. In reference to PeerTube, I will consider it in the future (currently, I don't have a lot of time). Thanks for the suggestion.
